src/AEO.Solution/admin/WebApp/Models/ViewModel/ManagementViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

 
namespace WebApp.Models
{
    public class RoleViewModel
    {
        [Required]
        [DisplayName("角色")]
        public string Name { get; set; }
    }
    public class ManagementViewModel
    {
        public ICollection<ApplicationRole> Roles { get; set; }
        public ICollection<ApplicationUser> Users { get; set; }
    }
    public class AccountRecordViewModel
    {
        public ApplicationUser User { get; set; }
        public ICollection<ApplicationRole> Roles { get; set; }
    }
    public class AttachRoleViewModel
    {
        [Required]
        public string UserId { get; set; }
        [Required]
        public string RoleName { get; set; }
    }
    public class AccountViewModel
    {
        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "密码长度(6-100)。", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "密码")]
        public string Password { get; set; }
        public int TenantId { get; set; }
        public string TenantName { get; set; }
        public string Role { get; set; }
    }
}

src/AEO.Solution/admin/WebApp/Controllers/ManagementController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Repository.Pattern.UnitOfWork;
using WebApp.Models;

namespace WebApp.Controllers
{
  [Authorize]
  public class ManagementController : Controller
  {
    private ApplicationUserManager userManager;
    private ApplicationRoleManager roleManager;
    private readonly IUnitOfWorkAsync _unitOfWork;
    private ApplicationDbContext dbContext => HttpContext.GetOwinContext().Get<ApplicationDbContext>();
    public ApplicationUserManager UserManager
    {
      get => this.userManager ?? this.HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
      private set => this.userManager = value;
    }
    public ApplicationRoleManager RoleManager
    {
      get => this.roleManager ?? this.HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
      private set => this.roleManager = value;
    }

    public ManagementController(
            IUnitOfWorkAsync _unitOfWork
         ) => this._unitOfWork = _unitOfWork;

    private async Task<ActionResult> _Index()
    {
      //set default value
      var companyRepository = this._unitOfWork.RepositoryAsync<Company>();
      this.ViewBag.CompanySelectList = await companyRepository.Queryable().Select(r => new SelectListItem { Text = r.Name, Value = r.Id.ToString() }).ToArrayAsync();

      this.ViewBag.RoleSelectList = await this.RoleManager.Roles.Select(r => new SelectListItem { Text = r.Name, Value = r.Name }).ToArrayAsync();
      try
      {
        this.ViewBag.MaxRolesCount = this.UserManager.Users.Max(u => u.Roles.Count);
      }
      catch (InvalidOperationException ex)
      {
        this.ViewBag.MaxRolesCount = 0;
        Console.WriteLine(ex);
      }
      return this.View("Index", new ManagementViewModel
      {
        Users = await this.UserManager.Users.OrderBy(x => x.UserName).ToListAsync(),
        Roles = await  this.RoleManager.Roles.OrderBy(x => x.Name).ToListAsync()
      });
    }
    [Route("management/index", Name = "角色管理", Order = 1)]
    public async Task<ActionResult> Index()
    {
      if (this.RoleManager.Roles.Count() == 0)
      {
      await  this.RoleManager.CreateAsync(new ApplicationRole() { Name = "admin" });

      }

      return await this._Index();
    }



    [HttpPost]
    [Route("management/roles")]
    public async Task<ActionResult> AddRole(RoleViewModel model)
    {
      if (this.ModelState.IsValid)
      {
        var result = await this.RoleManager.CreateAsync(new ApplicationRole { Name = model.Name });
        if (result.Succeeded)
        {
          //RedirectToAction("Index");
          return await this._Index();
        }
        else
        {
          this.AddErrors(result);
        }
      }
      return await this._Index();
    }
    [HttpGet]
    [Route("management/roles/{id}")]
    public async Task<ActionResult> DeleteRole(string id)
    {
      var role = await this.RoleManager.FindByIdAsync(id);
      if (role != null)
      {
        await this.RoleManager.DeleteAsync(role);
      }
      return this.RedirectToAction("Index");
    }
    [HttpPost]
    [Button("Attach")]
    [Route("management/account/roles")]
    public async Task<ActionResult> AttachRole(AttachRoleViewModel model)
    {
      if (this.ModelState.IsValid)
      {
        var result = await this.UserManager.AddToRoleAsync(model.UserId, model.RoleName);
        if (result.Succeeded)
        {
          return this.RedirectToAction("Index");
        }
        else
        {
          this.AddErrors(result);
        }
      }
      return await this._Index();
    }
    [HttpPost]
    [Button("Purge")]
    [Route("management/account/roles")]
    public async Task<ActionResult> PurgeRole(AttachRoleViewModel model)
    {
      if (this.ModelState.IsValid)
      {
        var result = await this.UserManager.RemoveFromRoleAsync(model.UserId, model.RoleName);
        if (result.Succeeded)
        {
          return this.RedirectToAction("Index");
        }
        else
        {
          this.AddErrors(result);
        }
      }
      return await this._Index();
    }
    [HttpPost]
    [Route("management/account")]
    public async Task<ActionResult> AddAccount(AccountViewModel model)
    {
      if (this.ModelState.IsValid)
      {
        var tenant =await this.dbContext.Tenants.Where(x => x.Id == model.TenantId).FirstOrDefaultAsync();
        var user = new ApplicationUser() { UserName = model.UserName, Email = model.Email, TenantDb = tenant.ConnectionStrings, TenantName = tenant.Name };
        var result = await this.UserManager.CreateAsync(user, model.Password);
        if (result.Succeeded)
        {
          result = await this.UserManager.AddToRoleAsync(user.Id, model.Role);
          //return RedirectToAction("Index");
        }
        else
        {
          this.AddErrors(result);
        }
      }
      return await this._Index();
    }
    [HttpGet]
    [Route("management/account/{id}")]
    public async Task<ActionResult> DeleteAccount(string id)
    {
      var user = await this.UserManager.FindByIdAsync(id);
      if (user != null)
      {
        await this.UserManager.DeleteAsync(user);
      }
      return this.RedirectToAction("Index");
    }
    private void AddErrors(IdentityResult result)
    {
      foreach (var error in result.Errors)
      {
        this.ModelState.AddModelError("", error);
      }
    }
  }
}

src/AEO.Solution/admin/WebApp/Views/Management/Index.cshtml
@using WebApp.Models
@model ManagementViewModel

@{
  ViewData["Title"] = "角色分配";
  ViewData["PageName"] = "management";
  ViewData["Heading"] = "<i class='fal fa-users text-primary'></i>  角色分配";
  ViewData["Category1"] = "系统管理";
  ViewData["PageDescription"] = "";
}
<div class="row">
  <div class="col-md-3">
    <div class="card border  m-auto m-lg-0">
      @Html.Partial("_AddRolePartial", new RoleViewModel())
      <ul class="list-group list-group-flush">
        @foreach (var role in Model.Roles)
        {
          <li class="list-group-item d-flex">
            <div class="flex-grow-1 align-self-center"> @role.Name </div>
            <form action="/management/roles/@role.Id" method="get" class="flex-shrink-1 text-right" role="form">
              @Html.AntiForgeryToken()
              <button type="submit" value="删除" class="btn btn-sm btn-danger">删除</button>
            </form>
          </li>
        }
      </ul>
    </div>

  </div>
  <div class="col-md-9">
    <div class="card border  m-auto m-lg-0">
      <div class="card-header bg-trans-gradient py-2 pr-2 d-flex align-items-center flex-wrap">
        <!-- we wrap header title inside a span tag with utility padding -->
        <div class="card-title text-white">分配角色</div>

      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table id="account-table" class="table table-bordered">
            <thead>
              <tr>
                <th>账号</th>
                <th>全称</th>
                <th>所属角色</th>
                <th>追加角色</th>
                <th>删除角色</th>
              </tr>
            </thead>
            @foreach (var user in Model.Users)
            {
              @Html.Partial("_AccountRecordPartial", new AccountRecordViewModel { User = user, Roles = Model.Roles })
            }
          </table>
        </div>
      </div>
    </div>
  </div>

</div>


@section ScriptsBlock {
  <script type="text/javascript">
    //上传导入参数设定
    const entityname = "management";
    $(document).ready(function () {
      $('#addrolesform').bootstrapValidator({
        feedbackIcons: {
          valid: 'glyphicon glyphicon-ok',
          invalid: 'glyphicon glyphicon-remove',
          validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
          Name: {
            validators: {
              notEmpty: {
                message: '请输入新的角色'
              }
            }
          }
        }
      });
      $('#adduserform').bootstrapValidator({
        feedbackIcons: {
          valid: 'glyphicon glyphicon-ok',
          invalid: 'glyphicon glyphicon-remove',
          validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
          Name: {
            validators: {
              notEmpty: {
                message: '请输入新的账号'
              }
            }
          },
          Email: {
            validators: {
              notEmpty: {
                message: '请输入邮件地址'
              },
              emailAddress: {
                message: '请输入有效的邮件地址'
              }
            }
          },
          Password: {
            validators: {
              notEmpty: {
                message: '请输入密码'
              }
            }
          }
        }
      });
    });
  </script>

}

src/AEO.Solution/admin/WebApp/Views/Management/_AccountRecordPartial.cshtml
@using WebApp.Models
@model AccountRecordViewModel

  <tr>
    <td>@Model.User.UserName</td>
    <td>@Model.User.FullName</td>
    <td>
      @for (int i = 0, max = (int)ViewBag.MaxRolesCount; i < max; i++)
      {

        if (i < Model.User.Roles.Count)
        {
          var role = Model.User.Roles.ElementAt(i);
          <span class="badge bg-color-greenLight">
            @Model.Roles.Single(r => r.Id == role.RoleId).Name
          </span>
        }




      }
    </td>

    <td>
      @Html.Partial("_AttachRolePartial", new AttachRoleViewModel { UserId = Model.User.Id })
    </td>
    <td>
      @Html.Partial("_DeleteAccountPartial", Model.User)
    </td>
  </tr>

src/AEO.Solution/admin/WebApp/Views/Management/_AddAccountPartial.cshtml
@using WebApp.Models
@model AccountViewModel

@using (Html.BeginForm("Account", "Management", FormMethod.Post, new { @class = "form-inline", role = "form",id="adduserform" }))
{
    @Html.AntiForgeryToken()

<div class="form-group">

    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-users"></i></span>
        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", placeholder = "账号" })
    </div>
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "email" })
    </div>
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-key"></i></span>
        @Html.TextBoxFor(m => m.Password, new { @class = "form-control", placeholder = "密码" })
    </div>
    <div class="input-group">
        @Html.DropDownListFor(m => m.Role, (SelectListItem[])ViewBag.RoleSelectList, null, new { @class = "form-control" })
    </div>
    <div class="input-group">
        @Html.DropDownListFor(m => m.CompanyCode, (SelectListItem[])ViewBag.CompanySelectList, null, new { @class = "form-control" })
    </div>
    <div class="input-group">
        <input type="submit" class="btn btn-primary" value="注册" />
    </div>
</div>

     
   
   
}

src/AEO.Solution/admin/WebApp/Views/Management/_AddRolePartial.cshtml
@using WebApp.Models
@model RoleViewModel

  <form action="/management/roles" method="post" class="needs-validation" novalidate> 
    @Html.AntiForgeryToken()
    <div class="card-header bg-trans-gradient py-2 pr-2 d-flex align-items-center flex-wrap">
      <!-- we wrap header title inside a span tag with utility padding -->
      <div class="card-title text-white">角色</div>
      <div class="d-flex position-relative ml-auto" style="max-width: 10rem;">
        <i class="fal fa-users position-absolute pos-left fs-lg px-3 py-2 mt-1"></i>
        <input type="text" name="name" required class="form-control bg-subtlelight pl-6" placeholder="新角色">
      </div>
      <button type="submit" class="btn  btn-info ml-2 waves-effect waves-themed">
        新增
      </button>

    </div>
  </form>

src/AEO.Solution/admin/WebApp/Views/Management/_AttachRolePartial.cshtml
@using WebApp.Models
@model AttachRoleViewModel

<form action="/management/account/roles" method="post" class="form-inline" role="form">
    @Html.HiddenFor(m => m.UserId)
    <div class="col-md-6">
        @Html.DropDownListFor(m => m.RoleName, (SelectListItem[])ViewBag.RoleSelectList, null, new { @class = "form-control" })
    </div>
    <button type="submit" value="追加" class="btn btn-sm btn-success mr-1" name="Attach">追加</button>
    <button type="submit" value="删除" class="btn btn-sm btn-warning" name="Purge">删除</button>
</form>

src/AEO.Solution/admin/WebApp/Views/Management/_DeleteAccountPartial.cshtml
@using WebApp.Models
@model ApplicationUser

<form action="/management/account/@Model.Id" method="get" class="form-inline" role="form">
    @Html.AntiForgeryToken()
  <button type="submit" value="删除" class="btn btn-sm btn-danger">删除</button>
</form>

src/AEO.Solution/admin/WebApp/Views/Management/_RoleRecordPartial.cshtml
@using WebApp.Models

 
@model ApplicationRole

<tr>
    <td>@Model.Name</td>
    <td>
        <form action="/management/roles/@Model.Id" method="get" class="form-inline" role="form">
            @Html.AntiForgeryToken()
            <input type="submit" value="删除" class="btn btn-danger" />
        </form>
    </td>
</tr>